apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flaskapp-deployment
spec:
  replicas: 3 # Number of instances to run
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: us-central1-docker.pkg.dev/m-amr-project-one/cluster-storage/helloworld-flask-app   #artifact registry images path

        ports:
        - containerPort: 5000  # Port on which Flask app is running
---
apiVersion: v1
kind: Service
metadata:
  name: my-flaskapp-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 5000  # Port on which Flask app is running inside the pods
  type: LoadBalancer  